name: Docker-Pub
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Docker-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # secrets: DOCKER_USER, DOCKER_TOKEN
      - name: Build & Publish
        run: |
          repo=${GITHUB_REPOSITORY#*/}
          tag=${GITHUB_REF#refs/*/}
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
          docker image build -t $repo:$tag .
          docker tag $repo:$tag ${{secrets.DOCKER_USER}}/$repo:$tag
          docker push ${{secrets.DOCKER_USER}}/$repo:$tag
