name: Deploy-Server
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Deploy
        uses: amondnet/now-deployment@v2.0.3
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          now-org-id: ${{ secrets.ORG_ID}}  #Required
          now-project-id: ${{ secrets.PROJECT_ID}} #Required 
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
